Repository UCSolarCarTeam/Epsilon-Dashboard, pull requests merged in 2018-06, with the labels that each got.

#107 Jeffery/Queue name can be specified in config file
  README.md
  src/EpsilonDashboard/EpsilonDashboard.cpp
  src/InfrastructureLayer/InfrastructureContainer.cpp
  src/InfrastructureLayer/InfrastructureContainer.h
  src/InfrastructureLayer/Settings/I_Settings.h
  src/InfrastructureLayer/Settings/Settings.cpp
  src/InfrastructureLayer/Settings/Settings.h
  src/config.ini.example
Labels: Awaiting Changes

#125 Magnus/aux bms high voltage enable
  src/BusinessLayer/DataPopulators/AuxBmsPopulator.cpp
  src/BusinessLayer/DataPopulators/JsonDefines.h
  src/DataLayer/AuxBmsData/AuxBmsData.cpp
  src/DataLayer/AuxBmsData/AuxBmsData.h
  src/DataLayer/AuxBmsData/I_AuxBmsData.h
  src/PresenterLayer/AuxBmsPresenter/AuxBmsPresenter.cpp
  src/PresenterLayer/AuxBmsPresenter/AuxBmsPresenter.h
  src/ViewLayer/DebugDisplay/BatteryPage/BatteryUi/BatteryUi.cpp
  src/ViewLayer/DebugDisplay/BatteryPage/BatteryUi/BatteryUi.h
  src/ViewLayer/DebugDisplay/BatteryPage/BatteryUi/BatteryUi.ui
  src/ViewLayer/DebugDisplay/BatteryPage/BatteryUi/I_BatteryUi.h
  src/ViewLayer/DebugDisplay/BatteryPage/BatteryView/BatteryView.cpp
  src/ViewLayer/DebugDisplay/BatteryPage/BatteryView/BatteryView.h
Labels: Approved, Awaiting QA

#108 Jeffery/Logging Json data
  src/CommunicationLayer/CommunicationContainer.cpp
  src/CommunicationLayer/CommunicationLayer.pro
  src/CommunicationLayer/JsonReceiver/JsonReceiver.cpp
  src/CommunicationLayer/JsonReceiver/JsonReceiver.h
  src/CommunicationLayer/Logging/Logging.cpp
  src/CommunicationLayer/Logging/Logging.h
  src/InfrastructureLayer/Settings/I_Settings.h
  src/InfrastructureLayer/Settings/Settings.cpp
  src/InfrastructureLayer/Settings/Settings.h
  src/config.ini.example
Labels: Awaiting QA
